type MyCapitalize<S extends string> = S extends `${infer F}${infer R}` ? `${Uppercase<F>}${R}` : ''

// 这里的 uppercase 可以换成自选的类型映射
// 类似这样的
// type Letter = {
//     a: 'A'
//     b: 'B'
//     c: 'C'
//     d: 'D'
//     e: 'E'
//     f: 'F'
//     g: 'G'
//     h: 'H'
//     i: 'I'
//     j: 'J'
//     k: 'K'
//     l: 'L'
//     m: 'M'
//     n: 'N'
//     o: 'O'
//     p: 'P'
//     q: 'Q'
//     r: 'R'
//     s: 'S'
//     t: 'T'
//     u: 'U'
//     v: 'V'
//     w: 'W'
//     x: 'X'
//     y: 'Y'
//     z: 'Z'
//   }
